### PR TITLE
Update website

### LINKED ISSUE #118: Update website for Hackathon
Given the peak in website visit during the hackathon, we should update our website. At least do the following:
- update description,
- add logo
- embed [flowchart](https://drive.google.com/file/d/1BqYuqOvTUyPTHhb3z19rktEv6lZU3ehM/view?usp=sharing)
- update API doc to reflect latest branch (videotape-giraffe)

I see that @po09i opened a PR to update the readme https://github.com/shimming-toolbox/shimming-toolbox/pull/113, but this change will not affect the website shimming-toolbox.org, as the README.md is not included in the doc build. 

I suggest to include the README in the build (instead of duplicating the content in the index.md).

### PR DESCRIPTION
**Pull request by po09i**
This PR
- Updates the API doc
- Adds extension to mkdocs.yml
- Adds embed flowchart
- Update description
- Add logo

Fixes [issue in shimming-toolbox](https://github.com/shimming-toolbox/shimming-toolbox/issues/118)

### CODE REVIEW

**Comment by jcohenadad** [comment]
@po09i is there a way to see the generated doc on the website for this branch, before merging it?

**Comment by po09i** [comment]
> @po09i is there a way to see the generated doc on the website for this branch, before merging it?

You need to locally look at the branch, download mkdocs, and run mkdocs serve.
Here is more [info](https://www.mkdocs.org/#getting-started)

**Comment by po09i** [comment]
The flowchart is really big and does not look great in a webpage, any idea how to fix that?
Screen Shot 2020-06-15 at 22 55 15

**Comment by jcohenadad** [comment]
How about just sharing the link for now? We will deal with embedding later

**Comment by jcohenadad** [comment]
Also, I would not put the flowchart under contributing, because this is also dedicated to users. I would à section “overview” between intro and getting started

**Comment by jcohenadad** [comment]
Re: flowchart: is it possible to zoom in, on the embedded flowchart? If so, then it is not too problematic

**Comment by po09i** [comment]
It is possible to zoom in.
There is currently a overview subsection in introduction, it could go there.

**Comment by jcohenadad** [comment]
If it is possible to zoom in then it’s fine.
I would personally make overview the main heading, and writhing it: intro, flowchart, etc.

**Comment by po09i** [comment]
Ready for review
I commented out in the "mkdocs.yml" so that only pages that are filled are displayed. This means the support and hardware sections won't display with an empty page.

**Review by jcohenadad — APPROVED** [review]
looks beautiful! thank you @po09i

**Pull request merged**
